# Generated by Django 4.1.6 on 2023-06-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('fabricante', models.CharField(max_length=30)),
            ],
        ),
    ]
