# Generated by Django 4.1.6 on 2023-06-08 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cataleg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('comprado', models.BooleanField(default=False)),
                ('productoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cataleg.productos')),
            ],
        ),
    ]
